theme: jekyll-theme-hacker
title: DC44141 - Glasgow Defcon Hacker Meetup Page
description: Glasgow Defcon meetup on the first Tuesday of every month at the GCU Students’ Association building from 6:30pm.
avatar: "images/Glasgow_Defcon_Logo_400x400.jpeg"
